name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.3
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.2.0
  - pyarrow=2.0
  - ipywidgets=7.7.1
  - pip:
      - wandb==0.12.17